title: scrotiegg
profile_img: /assets/img/scrotiegg.png
icon_img: /assets/img/scrotiegg-icon.png

name: "scrotiegg"
job: "first memecoin to embrace failure"

phone_number: dial at your own risk
address: lost somewhere on the blockchain
email: never-reply@scrotiegg.fun

x_username: scrotiegg           # X
discord_username: scrotiegg     # Discord
instagram_username: scrotiegg   # Instagram
tiktok_username: scrotiegg      # TikTok
reddit_username: scrotiegg      # Reddit
youtube_username: scrotiegg     # YouTube
github_username: scrotiegg      # GitHub
facebook_username: scrotiegg    # Facebook
threads_username: scrotiegg     # Threads
spotify_username: scrotiegg     # Spotify

blog_url: https://scrotiegg.fun

baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
