title: scrotiegg – failure is the utility
profile_img: /assets/img/scrotiegg.png     # coloque aqui a imagem do ovo cabeludo!
icon_img: /assets/img/scrotiegg-icon.png   # coloque aqui o ícone engraçado

name: "scrotiegg (the original hairy egg)"
job: "first memecoin to embrace failure"

phone_number: dial at your own risk
address: lost somewhere on the blockchain
email: mailbox@scrotiegg.fun  # use seu e-mail ou uma fake divertida!
linkedin_username: nobody-hired-us
github_username: scrotiegg
instagram_username: scrotiegg
twitter_username: scrotiegg
facebook_username: scrotiegg
youtube_username: scrotiegg
blog_url: https://scrotiegg.fun # ou um link para um 404 meme se preferir

baseurl: # (normalmente deixe em branco)

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
